### PR TITLE
This Adminv2ContainerComponent lets you create resources that get add…

### PR DESCRIPTION
**Pull request by vinmmm**
…ed to a vertical list on the left. Resources can also be deleted. Uses localStorage still not api.

### CODE REVIEW

**Comment by ejaxon** [comment]
@vinmmm I'm confused a bit by why this is showing 138 files changed since it looks like there's actual new code only in 3 of them.

**Comment by vinmmm** [comment]
@ejaxon Because I did something goofy. Its only 5 files: The new component files in the adminv2 directory and the old file with the new import: ReentryAdminHome.js. Need me to redo?

**Comment by ejaxon** [comment]
Naw. I'm going to merge.  But I think we need to get together and regroup on this soon. I'll post on Slack in the next day or so and we can figure out a time.

**Comment by vinmmm** [comment]
Cool.

**Pull request merged**
